--- 
title: "Representing data"
subtitle: "Refresher Mathematics for Economics course"
author: "Economics Department, University of Warwick"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
csl: economics-letters.csl
link-citations: yes
github-repo: eekostadinov/Refresher
url: 'https://github.com/eekostadinov/Refresher'
description: "Examples of representing data with R for undergraduate students in Economics"
---

# Preface {-}

This is a short e-book supporting the section on Data Appreciation of the [Refresher Mathematics for Economics course at Warwick](https://moodle.warwick.ac.uk/course/view.php?id=44183).

The book uses a variety of data sources to provides examples of representing data. The exposition is structured around three topics

1. [Representing differences in living standards across countries and over time](#ch1)
2. [Representing data on climate change](#ch2)
3. [Representing income inequality](#ch3)

Data is analyzed using R [@R] - one of the most commonly used programming languages for statistical computing and graphics. 

The purpose of the book is three-fold.

1. To enhance your understanding of what data is and of different types of data structures, by using real world examples.
2. To provide examples of meaningful ways for representing data - in different contexts, using real-world data.
3. To provide a brief introduction to R and some of its common packages.

With reference to point 3. above, the book presents all R codes used together with the outputs from the code (such as graphs and tables). The codes are fully replicable - if you run all the blocks of code in your own R/RStudio installation (or on the cloud) in the order that they appear within each chapter, you will get identical results. This being said, a complete introduction to R is beyond the scope of this course and not all of the code will be explained in detail. You are nonetheless strongly encouraged to run the code yourself, and hopefully learn intuitively key aspects of the syntax of the language. Still, some parts of the document will include relatively advanced code, so do not worry if you do not understand everything (or even most of the code).

## How to read this book

We imagine that there could be two possible ways of reading the book, depending on whether you want to simply reflect on different ways of visualizing the data, or you also want to gain some understanding of coding in R.

If you are not interested in using R to replicate the results yourself, then you can simply read through the e-book, reflect on the tables and figures presented, and their interpretation. This should be sufficient to gain some understanding of the variety of different types of tables and charts used to represent data.

However, a more thorough way of engaging with the book and with data, is to additionally try to reflect on the codes producing the representations, ideally by replicating them in your own R/RStudio installation or on the cloud. As some understanding of data analysis and coding are part of the essential toolkit of an economist, we would strongly recommend this approach. 

### How to run the codes yourself

To run the codes and replicate the results yourself, you need to run R either on your own computer or on the cloud. We propose two different ways of doing this.

First, if you would like to run the codes interactively (with the ability to make small changes in code and see how output is affected), but not install R on your machine yet, we have created a virtual online environment on [mybinder.org](https://mybinder.org) where the codes from different chapters of the book can be run interactively. You can access the virtual environment [here](https://mybinder.org/v2/gh/eekostadinov/Refresher/notebooks). Please do note that it is possible to get an error message - if this is the case try refreshing the page several times until (and it should) it works. This is perfectly sufficient for exploring all the codes related to the book and playing around by exploring how small changes in the code affect the output.

Alternatively, you can install R and RStudio (both R and RStudio are free and open-source) on your own machine and replicate the codes in your own RStudio installation. The advantage of this approach, is that you will be able to use the software for subsequent work on data analysis - something that may be useful during your degree. Additionally, after the installation, running from your own installation will likely work faster than in the virtual environment on the cloud. 

- If you are using a University computer, R and RStudio should already be installed. 
- To install R and RStudio on your own personal computer, first download the most recent version of R for your operating system from [CRAN](https://cran.r-project.org/) and follow the instructions there to install. Next, download the most recent version of RStudio Desktop for your operating system from [Posit website](https://posit.co/products/open-source/rstudio/) and follow the instructions there to install. 

Once you have your own installation, you will be able to copy chunks of code from the e-book into a script in your RStudio editor, and run from there. To make this easier, you can download all the data and Rscripts (containing all code) for the chapters from the [book's GitHub repository](https://github.com/eekostadinov/Refresher/tree/data-and-rscripts). Follow the instructions there to set up your local environment.

## Additional resources on R

Beyond this Refresher course, if you would like to learn more about programming with R, the Department provides an online course  *Introduction to R* [here](https://moodle.warwick.ac.uk/course/view.php?id=30899). The course is open for all students, not for credit, and you can enroll by simply clicking on the link. 

## Additional resources on transitioning to economics

While the discussion in this e-book aims to be at a level appropriate for students joining degrees with economics, the applications invariably (although rarely) make use of some economic concepts and vocabulary which might be new to some students. The Department provides an online course *Transitioning to Economics* [here](https://moodle.warwick.ac.uk/course/view.php?id=38056) which provides introductory discussions to some key economic concepts, some of which relevant to those discussed in this e-book. Specific concepts where relevant resources are available there are explicitly referenced within the e-book, but in general we would like to encourage you to engage with the above course as well, not only for the purposes of following the content here. The course is open for all students, not for credit, and you can enroll by simply clicking on the link. 

