<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Representing income inequality | Representing data</title>
  <meta name="description" content="Examples of representing data with R for undergraduate students in Economics" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Representing income inequality | Representing data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Examples of representing data with R for undergraduate students in Economics" />
  <meta name="github-repo" content="eekostadinov/Refresher" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Representing income inequality | Representing data" />
  
  <meta name="twitter:description" content="Examples of representing data with R for undergraduate students in Economics" />
  

<meta name="author" content="Economics Department, University of Warwick" />


<meta name="date" content="2023-09-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch2.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Appreciation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#how-to-read-this-book"><i class="fa fa-check"></i><b>0.1</b> How to read this book</a>
<ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#how-to-run-the-codes-yourself"><i class="fa fa-check"></i><b>0.1.1</b> How to run the codes yourself</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="some-basics.html"><a href="some-basics.html"><i class="fa fa-check"></i><b>1</b> Some basics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="some-basics.html"><a href="some-basics.html#data"><i class="fa fa-check"></i><b>1.1</b> Data</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="some-basics.html"><a href="some-basics.html#cross-sectional-time-series-and-panel-data"><i class="fa fa-check"></i><b>1.1.1</b> Cross-sectional, time-series, and panel data</a></li>
<li class="chapter" data-level="1.1.2" data-path="some-basics.html"><a href="some-basics.html#visualizing-the-structure-of-your-data"><i class="fa fa-check"></i><b>1.1.2</b> Visualizing the structure of your data</a></li>
<li class="chapter" data-level="1.1.3" data-path="some-basics.html"><a href="some-basics.html#categorical-and-quantitative-variables"><i class="fa fa-check"></i><b>1.1.3</b> Categorical and quantitative variables</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="some-basics.html"><a href="some-basics.html#a-note-on-r-packages"><i class="fa fa-check"></i><b>1.2</b> A note on R packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>2</b> Representing differences in living standards across countries and over time</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch1.html"><a href="ch1.html#representing-cross-sectional-data-cross-country-differences-in-living-standards-in-2019"><i class="fa fa-check"></i><b>2.1</b> Representing cross sectional data: Cross-country differences in living standards in 2019</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ch1.html"><a href="ch1.html#loading-data"><i class="fa fa-check"></i><b>2.1.1</b> Loading data</a></li>
<li class="chapter" data-level="2.1.2" data-path="ch1.html"><a href="ch1.html#summary-of-key-variables"><i class="fa fa-check"></i><b>2.1.2</b> Summary of key variables</a></li>
<li class="chapter" data-level="2.1.3" data-path="ch1.html"><a href="ch1.html#maps-for-fun"><i class="fa fa-check"></i><b>2.1.3</b> Maps (for fun)</a></li>
<li class="chapter" data-level="2.1.4" data-path="ch1.html"><a href="ch1.html#histograms"><i class="fa fa-check"></i><b>2.1.4</b> Histograms</a></li>
<li class="chapter" data-level="2.1.5" data-path="ch1.html"><a href="ch1.html#quantiles"><i class="fa fa-check"></i><b>2.1.5</b> Quantiles</a></li>
<li class="chapter" data-level="2.1.6" data-path="ch1.html"><a href="ch1.html#quantile-function"><i class="fa fa-check"></i><b>2.1.6</b> Quantile function</a></li>
<li class="chapter" data-level="2.1.7" data-path="ch1.html"><a href="ch1.html#visualizing-distribution-within-and-between-regions"><i class="fa fa-check"></i><b>2.1.7</b> Visualizing distribution within and between regions</a></li>
<li class="chapter" data-level="2.1.8" data-path="ch1.html"><a href="ch1.html#representing-relationships-between-continuous-variables"><i class="fa fa-check"></i><b>2.1.8</b> Representing relationships between continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ch1.html"><a href="ch1.html#representing-time-series-data-real-gdp-per-capita-in-uk-over-time"><i class="fa fa-check"></i><b>2.2</b> Representing time-series data: Real GDP per capita in UK over time</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ch1.html"><a href="ch1.html#time-series-line-plots"><i class="fa fa-check"></i><b>2.2.1</b> Time-series line plots</a></li>
<li class="chapter" data-level="2.2.2" data-path="ch1.html"><a href="ch1.html#time-series-line-plots-of-the-log-transformation"><i class="fa fa-check"></i><b>2.2.2</b> Time-series line plots of the log transformation</a></li>
<li class="chapter" data-level="2.2.3" data-path="ch1.html"><a href="ch1.html#recessions"><i class="fa fa-check"></i><b>2.2.3</b> Recessions</a></li>
<li class="chapter" data-level="2.2.4" data-path="ch1.html"><a href="ch1.html#growth-rates"><i class="fa fa-check"></i><b>2.2.4</b> Growth rates</a></li>
<li class="chapter" data-level="2.2.5" data-path="ch1.html"><a href="ch1.html#distributions-again"><i class="fa fa-check"></i><b>2.2.5</b> Distributions again</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ch1.html"><a href="ch1.html#representing-panel-data-cross-country-differences-in-living-standards-over-time---convergence-and-divergence"><i class="fa fa-check"></i><b>2.3</b> Representing panel data: Cross-country differences in living standards over time - convergence and divergence</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch2.html"><a href="ch2.html"><i class="fa fa-check"></i><b>3</b> Representing climate change</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch2.html"><a href="ch2.html#global-trends"><i class="fa fa-check"></i><b>3.1</b> Global trends</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="ch2.html"><a href="ch2.html#monthly-global-surface-temperature"><i class="fa fa-check"></i><b>3.1.1</b> Monthly global surface temperature</a></li>
<li class="chapter" data-level="3.1.2" data-path="ch2.html"><a href="ch2.html#changes-in-ice-mass"><i class="fa fa-check"></i><b>3.1.2</b> Changes in ice mass</a></li>
<li class="chapter" data-level="3.1.3" data-path="ch2.html"><a href="ch2.html#sea-level"><i class="fa fa-check"></i><b>3.1.3</b> Sea level</a></li>
<li class="chapter" data-level="3.1.4" data-path="ch2.html"><a href="ch2.html#co2-concentration"><i class="fa fa-check"></i><b>3.1.4</b> CO2 concentration</a></li>
<li class="chapter" data-level="3.1.5" data-path="ch2.html"><a href="ch2.html#co2-emissions"><i class="fa fa-check"></i><b>3.1.5</b> CO2 emissions</a></li>
<li class="chapter" data-level="3.1.6" data-path="ch2.html"><a href="ch2.html#co2-emissions-and-gni-per-capita"><i class="fa fa-check"></i><b>3.1.6</b> CO2 emissions and GNI per capita</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ch2.html"><a href="ch2.html#uk-trends"><i class="fa fa-check"></i><b>3.2</b> UK trends</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="ch2.html"><a href="ch2.html#uk-temperatures"><i class="fa fa-check"></i><b>3.2.1</b> UK temperatures</a></li>
<li class="chapter" data-level="3.2.2" data-path="ch2.html"><a href="ch2.html#uk-rainfall"><i class="fa fa-check"></i><b>3.2.2</b> UK Rainfall</a></li>
<li class="chapter" data-level="3.2.3" data-path="ch2.html"><a href="ch2.html#uk-co2-emissions"><i class="fa fa-check"></i><b>3.2.3</b> UK CO2 emissions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch3.html"><a href="ch3.html"><i class="fa fa-check"></i><b>4</b> Representing income inequality</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch3.html"><a href="ch3.html#distribution-of-income-in-the-frs-201617"><i class="fa fa-check"></i><b>4.1</b> Distribution of income in the FRS 2016/17</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="ch3.html"><a href="ch3.html#summary-of-data"><i class="fa fa-check"></i><b>4.1.1</b> Summary of data</a></li>
<li class="chapter" data-level="4.1.2" data-path="ch3.html"><a href="ch3.html#distribution-of-income-dispersion-and-skewness"><i class="fa fa-check"></i><b>4.1.2</b> Distribution of income: dispersion and skewness</a></li>
<li class="chapter" data-level="4.1.3" data-path="ch3.html"><a href="ch3.html#income-differences-between-and-within-groups-of-individuals"><i class="fa fa-check"></i><b>4.1.3</b> Income differences between and within groups of individuals</a></li>
<li class="chapter" data-level="4.1.4" data-path="ch3.html"><a href="ch3.html#quantitative-measures-of-income-inequality"><i class="fa fa-check"></i><b>4.1.4</b> Quantitative measures of income inequality</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="ch3.html"><a href="ch3.html#cross-country-differences-in-income-inequality"><i class="fa fa-check"></i><b>4.2</b> Cross-country differences in income inequality</a></li>
<li class="chapter" data-level="4.3" data-path="ch3.html"><a href="ch3.html#income-inequality-over-time"><i class="fa fa-check"></i><b>4.3</b> Income inequality over time</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Representing data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch3" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Representing income inequality<a href="ch3.html#ch3" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter turns attention to representing the extent of income inequality using data.</p>
<p>For ease of replication, all the data used in the documented is available as an Excel file <code>data_ch3.xlsx</code> with different datasets saved as different tabs. To replicate the rest of the document in your own R installation, download the file and place it inside a folder on your computer. Then set the working directory in R to the folder where you placed the file. On my computer this is done as follows:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="ch3.html#cb144-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;/home/emil/Desktop/book&quot;</span>)</span></code></pre></div>
<p>In addition, run the following code to install all the R libraries that will be used for the analysis</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="ch3.html#cb145-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;readxl&quot;</span>)</span>
<span id="cb145-2"><a href="ch3.html#cb145-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb145-3"><a href="ch3.html#cb145-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb145-4"><a href="ch3.html#cb145-4" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;forcats&quot;</span>)</span>
<span id="cb145-5"><a href="ch3.html#cb145-5" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;pracma&quot;</span>)</span>
<span id="cb145-6"><a href="ch3.html#cb145-6" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;scales&quot;</span>)</span></code></pre></div>
<p>and load them</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="ch3.html#cb146-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb146-2"><a href="ch3.html#cb146-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb146-3"><a href="ch3.html#cb146-3" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb146-4"><a href="ch3.html#cb146-4" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb146-5"><a href="ch3.html#cb146-5" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb146-6"><a href="ch3.html#cb146-6" tabindex="-1"></a><span class="fu">library</span>(pracma)</span></code></pre></div>
<div id="distribution-of-income-in-the-frs-201617" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Distribution of income in the FRS 2016/17<a href="ch3.html#distribution-of-income-in-the-frs-201617" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Family Resources Survey (FRS), carried out by the ONS, with the NatCen, and NISRA, is an annual survey collecting information on a representative sample of UK households <span class="citation">(<a href="#ref-frs17">Office for National Statistics, Social and Vital Statistics Division, Department for Work and Pensions, National Centre for Social Research, 2023</a>)</span>. It includes rich information on the incomes and characteristics of individuals and households.</p>
<p>This section uses an excerpt from the FRS 2016/17 individual level data to provide some examples of representing key cross-sectional patterns related to the unequal distribution of income, and to discuss how income inequality can be measured. The data is not open-access, hence it is not provided with this document. Given this you will not be able to replicate this section (without obtaining the data), but the structure of the data is explained in sufficient detail for you to understand the code.</p>
<div id="summary-of-data" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Summary of data<a href="ch3.html#summary-of-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s start by loading the data and listing the first few rows</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="ch3.html#cb147-1" tabindex="-1"></a>frs <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;FRS2017.xlsx&quot;</span>)</span>
<span id="cb147-2"><a href="ch3.html#cb147-2" tabindex="-1"></a><span class="fu">head</span>(frs)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["age"],"name":[1],"type":["chr"],"align":["left"]},{"label":["educ"],"name":[2],"type":["chr"],"align":["left"]},{"label":["sex"],"name":[3],"type":["chr"],"align":["left"]},{"label":["income"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"Age 65 and over","2":"NA","3":"Male","4":"225"},{"1":"Age 65 and over","2":"NA","3":"Female","4":"110"},{"1":"Age 25 to 34","2":"Degree of equivalent","3":"Female","4":"0"},{"1":"Age 35 to 44","2":"Degree of equivalent","3":"Male","4":"1093"},{"1":"Age 65 and over","2":"A-level or equivalent","3":"Female","4":"671"},{"1":"Age 55 to 64","2":"A-level or equivalent","3":"Male","4":"76"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The data is a cross-section of 33252 observations on four variables from the 2016/17 financial year. An observation (row of the data) corresponds to an individual (aged 16 and over). The four variables are
- <code>age</code> - recording the age of the individual in bands
- <code>educ</code> - recording the highest education attainment of the individual in bands
- <code>sex</code> - recording the sex of the individual
- <code>income</code> - recording the individual’s total weekly income from all sources (including pensions and transfers) before tax.</p>
<p>To prepare the data for analysis
1. note that <code>age</code>, <code>educ</code> and <code>sex</code> are categorical (factor) variables which we can declare explicitly to avoid problems</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="ch3.html#cb148-1" tabindex="-1"></a><span class="co"># Declare variables as categorical</span></span>
<span id="cb148-2"><a href="ch3.html#cb148-2" tabindex="-1"></a>frs<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(frs<span class="sc">$</span>age)</span>
<span id="cb148-3"><a href="ch3.html#cb148-3" tabindex="-1"></a>frs<span class="sc">$</span>educ <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(frs<span class="sc">$</span>educ)</span>
<span id="cb148-4"><a href="ch3.html#cb148-4" tabindex="-1"></a>frs<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(frs<span class="sc">$</span>sex)</span>
<span id="cb148-5"><a href="ch3.html#cb148-5" tabindex="-1"></a></span>
<span id="cb148-6"><a href="ch3.html#cb148-6" tabindex="-1"></a><span class="co"># Change order of categories in `educ` in order of average income per group</span></span>
<span id="cb148-7"><a href="ch3.html#cb148-7" tabindex="-1"></a>frs<span class="sc">$</span>educ <span class="ot">&lt;-</span> <span class="fu">fct_reorder</span>(frs<span class="sc">$</span>educ, frs<span class="sc">$</span>income, <span class="at">.fun=</span>mean)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>note that <code>income</code> is recorded in the form of weekly income (i.e., measured in pounds per week). While equivalent, it is often more natural to think in terms of monthly or annual income. For this reason we will convert the income variable into approximate equivalent annual income by multiplying weekly income by 52 (the number of weeks in a year</li>
</ol>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="ch3.html#cb149-1" tabindex="-1"></a>frs<span class="sc">$</span>income <span class="ot">&lt;-</span> frs<span class="sc">$</span>income<span class="sc">*</span><span class="dv">52</span></span></code></pre></div>
<p>Now <code>income</code> is measured in pounds per year, and corresponds to total income from all sources before tax. Hencefort, by “income” we will mean specifically this notion of income. It should be noted that inequality metrics discussed below are specific to this particular definition of income, and would be different for alternative income concepts (e.g., income after taxes, or labour income only).</p>
<p>To get a sense of the data, calculate some summary statistics for all variables in the dataframe</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="ch3.html#cb150-1" tabindex="-1"></a><span class="fu">summary</span>(frs)</span></code></pre></div>
<pre><code>##               age                          educ           sex       
##  Age 16 to 24   :2456   GCSE or equivalent   :11265   Female:17509  
##  Age 25 to 34   :4821   A-level or equivalent: 5139   Male  :15743  
##  Age 35 to 44   :5334   Degree of equivalent : 7795                 
##  Age 45 to 54   :5678   Postgraduate         : 3162                 
##  Age 55 to 64   :5734   NA&#39;s                 : 5891                 
##  Age 65 and over:9229                                               
##      income      
##  Min.   :     0  
##  1st Qu.: 10088  
##  Median : 17576  
##  Mean   : 22751  
##  3rd Qu.: 28340  
##  Max.   :885768</code></pre>
<p>For categorical variables <code>summary()</code> reports the number of individuals in different categories. For example, we can see that the sample consists of 17509 females and 15743 males; most individuals’ highest educational attainment is GSCE or equivalent (11265 individuals).</p>
<p>For numerical variables (in this case only <code>income</code>) <code>summary()</code> reports key summary statistics from the distribution. At this stage we can already see that income is very unequally distributed. Unsurprisingly, the minimum of the support of income is 0 (some individuals reported no income), while the richest individual in the data reported annual income of £885768. 25% of individuals in the data receive income below £10088, 50% receive income below £17576 (the median), 75% receive income below £28340. Mean income (at £22751) is above median (at £17576) indicating that the distribution is asymmetric.</p>
</div>
<div id="distribution-of-income-dispersion-and-skewness" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Distribution of income: dispersion and skewness<a href="ch3.html#distribution-of-income-dispersion-and-skewness" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To understand the distribution of income in the data, we start by plotting a histogram of income</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="ch3.html#cb152-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs) <span class="sc">+</span> </span>
<span id="cb152-2"><a href="ch3.html#cb152-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>income), <span class="at">bins =</span> <span class="dv">100</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb152-3"><a href="ch3.html#cb152-3" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Annual income, GBP&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Number of observations&quot;</span>) <span class="sc">+</span> </span>
<span id="cb152-4"><a href="ch3.html#cb152-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Distribution of individual annual pre-tax income, FRS 2017&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Note that by default the histogram is plotted over the whole support of <code>income</code> in the sample (i.e. from £0 to £885768). This makes the graph look somewhat peculiar - it looks as if there are no observations with income above £375000 but this is misleading as in fact there are (we know one observation has £885768) but the corresponding bars are so small that they are effectively invisible.</p>
<p>To focus on the part of the distribution where most of the mass lies, we can restrict the horizontal axis to the 99th quantile of the distribution only</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="ch3.html#cb153-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs) <span class="sc">+</span> </span>
<span id="cb153-2"><a href="ch3.html#cb153-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>income), <span class="at">bins =</span> <span class="dv">100</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb153-3"><a href="ch3.html#cb153-3" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Annual income, GBP&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Number of observations&quot;</span>) <span class="sc">+</span> </span>
<span id="cb153-4"><a href="ch3.html#cb153-4" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="fu">quantile</span>(frs<span class="sc">$</span>income,<span class="fl">0.99</span>)) <span class="sc">+</span></span>
<span id="cb153-5"><a href="ch3.html#cb153-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Distribution of individual annual pre-tax income, FRS 2017, Bottom 99 percent&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>representing the income distribution within the bottom 99 percent of individuals by income only.</p>
<p>Two features of the distribution are immediately clear:
1. the distribution is highly disperse - there are large income differences between individuals.
2. the distribution is very strongly positively skewed - characterised by a long and thin right tail, with most observations found in the extreme left of the distribution.</p>
<p>It is clear that income is very unequally distributed. One implication of this is that when we use measures of central tendency (such as mean or median income) to quantify living standards within a country (for example, in measures such as GNI or GDP per capita) we should recognise the fact that they do not necessarily account for “typical” incomes - relatively few individuals earn income very close to the mean or the median.</p>
<p>Some important aspects of inequality are reflected in standard summary statistics. For example, as we observed above, mean income (£22751) considerably exceeds median income (£17576), which is a feature the observed asymmetry (skewness) of the distribution. Exactly 50% of individuals of the data receive income below £17576 (the median) but a much larger fraction of individuals receive income well below the mean.</p>
<p>To gain further quantitative understanding of the unequal distribution of income, it is informative to calculate some quantiles</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="ch3.html#cb154-1" tabindex="-1"></a><span class="fu">quantile</span>(frs<span class="sc">$</span>income, <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="at">by=</span><span class="fl">0.1</span>))</span></code></pre></div>
<pre><code>##   10%   20%   30%   40%   50%   60%   70%   80%   90% 
##  4264  8476 11544 14508 17576 20956 25324 31824 43368</code></pre>
<p>10% of individuals in the data receive less than £4264 pr year; 20% receive less than £8476 and so forth. One thing that we observe is that the fraction of people receiving less than average income is more than 60% (but less than 70%). Comparisons between different quantiles is very informative about both dispersion and assymetry (and as we will see later is the basis of some popular quantitative measures of income inequality). In particular, we observe large differences between quantiles (indicatig disperison) with differences increasing at higher incomes (indicating assymetry).</p>
</div>
<div id="income-differences-between-and-within-groups-of-individuals" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Income differences between and within groups of individuals<a href="ch3.html#income-differences-between-and-within-groups-of-individuals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The above discussion referred to overall differences in income between individuals. Important aspects of inequality are about differences between (and within) groups. This section illustrates such differences on the basis of the categorical variables observed in the data: <code>sex</code>, <code>age</code>, <code>educ</code>.</p>
<div id="inequality-between-sexes" class="section level4 hasAnchor" number="4.1.3.1">
<h4><span class="header-section-number">4.1.3.1</span> Inequality between sexes<a href="ch3.html#inequality-between-sexes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>It is well known that there are systematic income differences between men and women. To explore these within this data, start by plotting separate histograms by sex:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="ch3.html#cb156-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs, <span class="fu">aes</span>(<span class="at">x=</span>income, <span class="at">fill=</span>sex,  <span class="at">y =</span> ..density..)) <span class="sc">+</span> </span>
<span id="cb156-2"><a href="ch3.html#cb156-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>, <span class="at">position=</span><span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span> </span>
<span id="cb156-3"><a href="ch3.html#cb156-3" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)) <span class="sc">+</span></span>
<span id="cb156-4"><a href="ch3.html#cb156-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Annual income, GBP&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Density&quot;</span>) <span class="sc">+</span> </span>
<span id="cb156-5"><a href="ch3.html#cb156-5" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="fu">quantile</span>(frs<span class="sc">$</span>income,<span class="fl">0.99</span>)) <span class="sc">+</span></span>
<span id="cb156-6"><a href="ch3.html#cb156-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Distribution of individual annual pre-tax income, FRS 2017, By sex&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>It can be seen that the income distributions for men and women are different and, in particular, it appears that the distribution for men is shifted to the right relative to the distribution for women (for example, relative to men, women are more likely to be in the left tail of the overall distribution, and less likely in the right tail).</p>
<p>To get a more quantitative (if less rich) description of the differences, we can obtain a set of summary statistics (mean, median, 10th percentile, 90th percentile) for income by sex:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="ch3.html#cb157-1" tabindex="-1"></a>frs <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(income), <span class="at">median =</span> <span class="fu">median</span>(income), <span class="at">q10 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.1</span>), <span class="at">q90 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.9</span>))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["fct"],"align":["left"]},{"label":["mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["q10"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["q90"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"Female","2":"18037.59","3":"14664","4":"3317.6","5":"35266.4"},{"1":"Male","2":"27992.38","3":"21320","4":"7020.0","5":"52416.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Average income for men in the sample (£27992) far exceeds average income for women (£18037) and similarly for medians, 10th percentile and 90th percentile. For example, 90 percent of women receive less than £35266 while 90% of mean receive less than £52416.</p>
<p>As discussed before, a convenient way of presenting key summary statistics (25th percentile, median, 75th percentile, interquartile range) is through a box plot:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="ch3.html#cb158-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs,<span class="fu">aes</span>(<span class="at">y=</span>income, <span class="at">fill=</span>sex))<span class="sc">+</span></span>
<span id="cb158-2"><a href="ch3.html#cb158-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.5</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="fu">quantile</span>(frs<span class="sc">$</span>income,<span class="fl">0.95</span>)) <span class="sc">+</span></span>
<span id="cb158-3"><a href="ch3.html#cb158-3" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)) <span class="sc">+</span></span>
<span id="cb158-4"><a href="ch3.html#cb158-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Annual income, GBP&quot;</span>) <span class="sc">+</span> </span>
<span id="cb158-5"><a href="ch3.html#cb158-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Box plot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Annual income by sex, FRS 2017&quot;</span>, <span class="at">fill=</span><span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb158-6"><a href="ch3.html#cb158-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())<span class="sc">+</span> <span class="fu">coord_flip</span>() </span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Indeed we observe systematic differences in the distribution on income between men and women. It should be noted, however, that this accounts for only small part of the overall income inequality as the distributions of incomes within groups are still very unequal.</p>
</div>
<div id="income-differences-between-age-groups" class="section level4 hasAnchor" number="4.1.3.2">
<h4><span class="header-section-number">4.1.3.2</span> Income differences between age groups<a href="ch3.html#income-differences-between-age-groups" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>It is similarly well known income varies systematically over the life cycle, and some of the observed overall differences in incomes reflects differences in individuals’ age.</p>
<p>Given that we have 6 age groups, histograms will tend to be somewhat uninformative, but as before we can obtain a set of summary statistics for income by age</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="ch3.html#cb159-1" tabindex="-1"></a>frs <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(age) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(income), <span class="at">median =</span> <span class="fu">median</span>(income), <span class="at">q10 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.1</span>), <span class="at">q90 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.9</span>))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["age"],"name":[1],"type":["fct"],"align":["left"]},{"label":["mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["q10"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["q90"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"Age 16 to 24","2":"12800.47","3":"12584","4":"0.0","5":"23972.0"},{"1":"Age 25 to 34","2":"22967.61","3":"20436","4":"4004.0","5":"40300.0"},{"1":"Age 35 to 44","2":"29057.04","3":"23244","4":"5356.0","5":"54168.4"},{"1":"Age 45 to 54","2":"29444.12","3":"22100","4":"5184.4","5":"56784.0"},{"1":"Age 55 to 64","2":"22971.62","3":"17290","4":"1783.6","5":"45052.8"},{"1":"Age 65 and over","2":"17385.00","3":"13936","4":"6084.0","5":"31252.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>or use a box plot</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="ch3.html#cb160-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs,<span class="fu">aes</span>(<span class="at">y=</span>income, <span class="at">fill=</span>age))<span class="sc">+</span></span>
<span id="cb160-2"><a href="ch3.html#cb160-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="fu">quantile</span>(frs<span class="sc">$</span>income,<span class="fl">0.95</span>)) <span class="sc">+</span></span>
<span id="cb160-3"><a href="ch3.html#cb160-3" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Annual income, GBP&quot;</span>) <span class="sc">+</span> </span>
<span id="cb160-4"><a href="ch3.html#cb160-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Box plot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Income distribution by age, FRS 2017&quot;</span>, <span class="at">fill=</span><span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb160-5"><a href="ch3.html#cb160-5" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="sc">+</span></span>
<span id="cb160-6"><a href="ch3.html#cb160-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The age profile of income over age probably reflects life-cyclical patterns of labour income, where income increases on average as people progress through their careers, and then declines as they enter retirement. This clarifies that there are systematic income differences by age. It should be noted, however, that this accounts for only small part of the overall income inequality as distributions of incomes within age groups are still very unequal.</p>
</div>
<div id="income-differences-by-education" class="section level4 hasAnchor" number="4.1.3.3">
<h4><span class="header-section-number">4.1.3.3</span> Income differences by education<a href="ch3.html#income-differences-by-education" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Repeating the analysis for individuals with different education in terms of summary statistics</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="ch3.html#cb161-1" tabindex="-1"></a>frs <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(educ) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(income), <span class="at">median =</span> <span class="fu">median</span>(income), <span class="at">q10 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.1</span>), <span class="at">q90 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.9</span>))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["educ"],"name":[1],"type":["fct"],"align":["left"]},{"label":["mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["q10"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["q90"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"GCSE or equivalent","2":"18716.92","3":"16068","4":"4056","5":"34216.0"},{"1":"A-level or equivalent","2":"22404.97","3":"18148","4":"4004","5":"42390.4"},{"1":"Degree of equivalent","2":"28753.78","3":"22932","4":"4992","5":"54142.4"},{"1":"Postgraduate","2":"37993.58","3":"31096","4":"5980","5":"73585.2"},{"1":"NA","2":"14640.57","3":"13000","4":"4108","5":"24752.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>and box plot</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="ch3.html#cb162-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs,<span class="fu">aes</span>(<span class="at">y=</span>income, <span class="at">fill=</span>educ))<span class="sc">+</span></span>
<span id="cb162-2"><a href="ch3.html#cb162-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="fu">quantile</span>(frs<span class="sc">$</span>income,<span class="fl">0.95</span>)) <span class="sc">+</span></span>
<span id="cb162-3"><a href="ch3.html#cb162-3" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Annual income, GBP&quot;</span>) <span class="sc">+</span> </span>
<span id="cb162-4"><a href="ch3.html#cb162-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Box plot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Distribution of income by age, FRS 2017&quot;</span>, <span class="at">fill=</span><span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb162-5"><a href="ch3.html#cb162-5" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="sc">+</span></span>
<span id="cb162-6"><a href="ch3.html#cb162-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())<span class="sc">+</span> <span class="fu">coord_flip</span>() </span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>we observe that more education associates strongly with higher income, likely reflecting returns to education. For example, the median income among those with postgraduate degree (£31096) is just slightly below the 80th percentile of the overall income distribution (£31824), while the median for those with GCSE or equivalent (£16068) is just slightly above the 40th percentile of the overall income distribution (£14508). Again, while we observe systematic income differences between education groups, there is also significant income inequality within groups.</p>
</div>
</div>
<div id="quantitative-measures-of-income-inequality" class="section level3 hasAnchor" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Quantitative measures of income inequality<a href="ch3.html#quantitative-measures-of-income-inequality" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>While histograms allow us to represent the distribution of income in all its complexity, we are often interested in comparing the extent of inequality in different income distributions. For example:
- we might be interested in comparing different countries by income inequality. This amounts to comparing the whole distribution of income in Country A to the distribution of income in Country B.
- we might be interested in analyzing how income inequality changes over time in a given country. This amounts to comparing the distribution of income in Year A to the distribution of income in Year B.</p>
<p>As comparisons between histograms could be difficult (as observed) it would be more appropriate to use numerical measures of inequality instead. A numerical measure of inequality, is one that summarizes some aspect of the inequality into a single number. As inequality is a complex phenomenon, there are many different numerical measures, which emphasise different aspects of inequality. While a thorough discussion of different metrics is beyond the scope of the document, this section briefly outlines several popular metrics and illustrates their meaning through the data.</p>
<div id="percentile-ratios" class="section level4 hasAnchor" number="4.1.4.1">
<h4><span class="header-section-number">4.1.4.1</span> Percentile ratios<a href="ch3.html#percentile-ratios" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have already seen that comparison between different percentiles of the distribution is informative about important aspects of inequality. Percentile ratios (or p-ratios) are simply ratios of percentiles. Two common percentile ratios used to quantify inequality of income are the P50P10 ratio (the ratio between median income and the 10th percentile of income) and the P90P50 ratio (the ratio between the 90th percentile of income and median income).</p>
<p>For example, for the whole data, we can calculate the 10th, 50th and 90th percentiles, and the corresponding percentile ratios as follows</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="ch3.html#cb163-1" tabindex="-1"></a>frs <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">q10 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.1</span>), <span class="at">q50 =</span> <span class="fu">median</span>(income),  <span class="at">q90 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.9</span>), <span class="at">p90p50 =</span> q90<span class="sc">/</span>q50, <span class="at">p50p10 =</span> q50<span class="sc">/</span>q10)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["q10"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["q50"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["q90"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["p90p50"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p50p10"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"4264","2":"17576","3":"43368","4":"2.467456","5":"4.121951"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>We observe that those at the 90th percentile of the distribution have 2.47 times higher income than those at the median; while the latter have 4.12 times more income than those at the 10th percentile.</p>
<p>To show how p-ratios can be used to compare inequality across distributions, we can calculate the p-ratios for the income distributions within education groups in the data:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="ch3.html#cb164-1" tabindex="-1"></a>frs <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(educ) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">q10 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.1</span>), <span class="at">q50 =</span> <span class="fu">median</span>(income),  <span class="at">q90 =</span> <span class="fu">quantile</span>(income, <span class="fl">0.9</span>), <span class="at">p90p50 =</span> q90<span class="sc">/</span>q50, <span class="at">p50p10 =</span> q50<span class="sc">/</span>q10)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["educ"],"name":[1],"type":["fct"],"align":["left"]},{"label":["q10"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["q50"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["q90"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p90p50"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["p50p10"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"GCSE or equivalent","2":"4056","3":"16068","4":"34216.0","5":"2.129450","6":"3.961538"},{"1":"A-level or equivalent","2":"4004","3":"18148","4":"42390.4","5":"2.335817","6":"4.532468"},{"1":"Degree of equivalent","2":"4992","3":"22932","4":"54142.4","5":"2.360998","6":"4.593750"},{"1":"Postgraduate","2":"5980","3":"31096","4":"73585.2","5":"2.366388","6":"5.200000"},{"1":"NA","2":"4108","3":"13000","4":"24752.0","5":"1.904000","6":"3.164557"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>We have already seen that overall average and median incomes increase with education. However, we can now see that the distributions within groups become increasingly unequal with higher education.</p>
</div>
<div id="measures-of-concentration" class="section level4 hasAnchor" number="4.1.4.2">
<h4><span class="header-section-number">4.1.4.2</span> Measures of concentration<a href="ch3.html#measures-of-concentration" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>So far we have discussed two important features of the distribution of income - dispersion and asymmetry. Another important feature, which is somewhat distinct from the former, is that income distributions tend to be highly <em>concentrated</em>. Loosely, this means that relatively small fractions of the overall population receive relatively large shares of the total income. Some of the most popular metrics of income inequality (shares of top 10% or top 1%, GINI coefficient, etc) are in fact measures of concentration.</p>
<div id="lorenz-curve" class="section level5 hasAnchor" number="4.1.4.2.1">
<h5><span class="header-section-number">4.1.4.2.1</span> Lorenz curve<a href="ch3.html#lorenz-curve" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>To understand measures of concentration, suppose that we order all individuals in the data by increasing order of their income</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="ch3.html#cb165-1" tabindex="-1"></a>frs <span class="ot">&lt;-</span> frs <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(income)</span></code></pre></div>
<p>Calculate the quantile rank of each individual (i.e., the percentile of the overall distribution corresponding to the particular individual’s income)</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="ch3.html#cb166-1" tabindex="-1"></a>frs <span class="ot">&lt;-</span> frs <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">inc.qrank =</span> <span class="fu">row_number</span>(income)<span class="sc">/</span><span class="fu">length</span>(income))</span></code></pre></div>
<p>Now suppose that we move from the poorest to the richest individual, and for each we record the total income received by herself and those poorer, in a new variable, <code>cuminc</code> (for cummulative income)</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="ch3.html#cb167-1" tabindex="-1"></a>frs<span class="sc">$</span>cuminc <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(frs<span class="sc">$</span>income)</span></code></pre></div>
<p>Next, divide <code>cuminc</code> by the total amount of income earned by individuals in the data</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="ch3.html#cb168-1" tabindex="-1"></a>frs<span class="sc">$</span>cumincshare <span class="ot">&lt;-</span> frs<span class="sc">$</span>cuminc<span class="sc">/</span><span class="fu">sum</span>(frs<span class="sc">$</span>income)</span></code></pre></div>
<p>to obtain the cummulative income share at each quantile rank.</p>
<p>The mapping from quantile rank to cummulative income share is known as a the Lorenz curve. The Lorenz curve for income in the FRS data can be represented graphically as follows</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="ch3.html#cb169-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs) <span class="sc">+</span> </span>
<span id="cb169-2"><a href="ch3.html#cb169-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>inc.qrank, <span class="at">y=</span>cumincshare), <span class="at">col=</span><span class="st">&quot;tomato&quot;</span>) <span class="sc">+</span> </span>
<span id="cb169-3"><a href="ch3.html#cb169-3" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">by=</span><span class="fl">0.1</span>)) <span class="sc">+</span> </span>
<span id="cb169-4"><a href="ch3.html#cb169-4" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">by=</span><span class="fl">0.1</span>)) <span class="sc">+</span> </span>
<span id="cb169-5"><a href="ch3.html#cb169-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Quantile of income&quot;</span>) <span class="sc">+</span> </span>
<span id="cb169-6"><a href="ch3.html#cb169-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cummulative share of income&quot;</span>) <span class="sc">+</span></span>
<span id="cb169-7"><a href="ch3.html#cb169-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Lorenz curve&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>From the Lorenz curve, we can observe that, for example
- the bottom 50 % of individuals by income receive around 20% of all the income in the sample. Therefore, the top 50% receive around 80%.
- the bottom 90% of individuals receive around 68% of all the income. Therefore, the top 10 % receive the remaining 32%.
- the top 5% receive around 21% of all income
- and so forth.</p>
</div>
<div id="top-income-shares" class="section level5 hasAnchor" number="4.1.4.2.2">
<h5><span class="header-section-number">4.1.4.2.2</span> Top income shares<a href="ch3.html#top-income-shares" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The points on the Lorenz curve (known as Lorenz coordinates) are the basis of many popular measures of income inequality (and more specifically income concentration). Two common measures are as follows:</p>
<p>-the share of income of the top 10 %. We can obtain this by finding the share of the bottom 90 %</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="ch3.html#cb170-1" tabindex="-1"></a>lorenz_fun <span class="ot">&lt;-</span> <span class="fu">approxfun</span>(<span class="at">x=</span>frs<span class="sc">$</span>inc.qrank, <span class="at">y=</span>frs<span class="sc">$</span>cumincshare)</span>
<span id="cb170-2"><a href="ch3.html#cb170-2" tabindex="-1"></a><span class="fu">lorenz_fun</span>(<span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## [1] 0.6804861</code></pre>
<p>implying that the share of the top 10% in the FRS is approximately 32% of all income. This is in line with estimates from administrative data for the UK as a whole.</p>
<ul>
<li>the share of income of the top 1 $. We can obtain this by finding the share of the bottom 99 %</li>
</ul>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="ch3.html#cb172-1" tabindex="-1"></a><span class="fu">lorenz_fun</span>(<span class="fl">0.99</span>)</span></code></pre></div>
<pre><code>## [1] 0.9218844</code></pre>
<p>implying that the share of the top 1% in the FRS is approximately 9.2% of all income. This seems to be slightly lower than estimates from administrative data for the UK as a whole, likely due to underrepresentation of richest individuals in the survey.</p>
</div>
<div id="gini-coefficient" class="section level5 hasAnchor" number="4.1.4.2.3">
<h5><span class="header-section-number">4.1.4.2.3</span> Gini coefficient<a href="ch3.html#gini-coefficient" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Probably the best known measure of income inequality, the Gini coefficient, is in fact a measure of concentration related to the Lorenz curve. The figure below plots the actual empirical Lorenz curve for the FRS (in blue) together with
- a counterfactual Lorenz curve for an economy with “perfect equality” (in red). If all individuals in an economy receive the same income (perfect equality), and are ordered arbitrarily along the horizontal axis, then the “poorest” (arbitrarily defined) <span class="math inline">\(n\)</span>% of the population, would be receiving <span class="math inline">\(n\)</span>% of the total income. The Lorenz curve maps <span class="math inline">\(n\)</span> to <span class="math inline">\(n\)</span> and is therefore a straight line with slope 45 degrees.
- a counterfactual Lorenz curve for an economy with “perfect inequality” (in green). If all but one individuals in the economy receive no income, and one receives some (and therefore all the income), then the income share of the “all but one” will be 0 (implying horizontal portion of the Lorenz curve over <span class="math inline">\([0,1)\)</span>) and a discontinuous jump at <span class="math inline">\(1\)</span>.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="ch3.html#cb174-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs) <span class="sc">+</span> </span>
<span id="cb174-2"><a href="ch3.html#cb174-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>inc.qrank, <span class="at">y=</span>cumincshare, <span class="at">col=</span><span class="st">&quot;Lorenz curve, FRS&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb174-3"><a href="ch3.html#cb174-3" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">0</span>, <span class="at">xend=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="dv">1</span>, </span>
<span id="cb174-4"><a href="ch3.html#cb174-4" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">col=</span><span class="st">&quot;Lorenz curve under perfect equality&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb174-5"><a href="ch3.html#cb174-5" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">0</span>, <span class="at">xend=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="dv">0</span>, </span>
<span id="cb174-6"><a href="ch3.html#cb174-6" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">col=</span><span class="st">&quot;Lorenz curve under perfect inequality&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb174-7"><a href="ch3.html#cb174-7" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">1</span>, <span class="at">xend=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="dv">1</span>, </span>
<span id="cb174-8"><a href="ch3.html#cb174-8" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">col=</span><span class="st">&quot;Lorenz curve under perfect inequality&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb174-9"><a href="ch3.html#cb174-9" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Quantile of income&quot;</span>) <span class="sc">+</span> </span>
<span id="cb174-10"><a href="ch3.html#cb174-10" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cummulative share of income&quot;</span>) <span class="sc">+</span></span>
<span id="cb174-11"><a href="ch3.html#cb174-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Lorenz curves and Gini coefficient, 1&quot;</span>, <span class="at">color =</span> <span class="st">&quot;&quot;</span>) </span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Intuitively, the closer is the actual Lorenz curve to the perfect equality one, the more equal is the distribution; the closer to the perfect inequality one, the more unequal is the distribution. The Gini coefficient measures exactly how close the actual Lorenz curve is to the perfect inequality line and more specifically is defined as follows:</p>
<p>Let <span class="math inline">\(A\)</span> denote the area between the actual Lorenz curve and the perfect equality line, and <span class="math inline">\(B\)</span> denote the area between the perfect inequality line and the actual Lorenz curve:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="ch3.html#cb175-1" tabindex="-1"></a><span class="fu">ggplot</span>(frs) <span class="sc">+</span> </span>
<span id="cb175-2"><a href="ch3.html#cb175-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>inc.qrank, <span class="at">y=</span>cumincshare, <span class="at">col=</span><span class="st">&quot;Lorenz curve, FRS&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb175-3"><a href="ch3.html#cb175-3" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">0</span>, <span class="at">xend=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="dv">1</span>, <span class="fu">aes</span>(<span class="at">col=</span><span class="st">&quot;Lorenz curve under perfect equality&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb175-4"><a href="ch3.html#cb175-4" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">0</span>, <span class="at">xend=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="dv">0</span>, <span class="fu">aes</span>(<span class="at">col=</span><span class="st">&quot;Lorenz curve under perfect inequality&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb175-5"><a href="ch3.html#cb175-5" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">1</span>, <span class="at">xend=</span><span class="dv">1</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">yend=</span><span class="dv">1</span>, <span class="fu">aes</span>(<span class="at">col=</span><span class="st">&quot;Lorenz curve under perfect inequality&quot;</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Quantile of income&quot;</span>) <span class="sc">+</span> </span>
<span id="cb175-6"><a href="ch3.html#cb175-6" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x=</span>inc.qrank, <span class="at">ymin =</span> cumincshare, <span class="at">ymax =</span> inc.qrank, <span class="at">fill =</span> <span class="st">&quot;A&quot;</span>), <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb175-7"><a href="ch3.html#cb175-7" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x=</span>inc.qrank, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> cumincshare, <span class="at">fill =</span> <span class="st">&quot;B&quot;</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb175-8"><a href="ch3.html#cb175-8" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cummulative share of income&quot;</span>) <span class="sc">+</span></span>
<span id="cb175-9"><a href="ch3.html#cb175-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Lorenz curves and Gini coefficient, 2&quot;</span>, <span class="at">color =</span> <span class="st">&quot;&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Area&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Then the Gini coefficient is defined as</p>
<p><span class="math display">\[Gini = \frac{A}{A+B}\]</span></p>
<p>Note that since <span class="math inline">\(A+B=1/2\)</span>, the Gini coefficient is also equal to <span class="math inline">\(2A\)</span> or <span class="math inline">\(1-2B\)</span>. It is easy to see that the value of the Gini coefficient is a number between 0 and 1, with 0 indicating perfect equality, and 1 indicating perfect inequality.</p>
<p>One way to calculate the Gini coefficient in our data is to obtain the area <span class="math inline">\(B\)</span> as the definite integral of the Lorenz curve from 0 to 1. Integrating the Lorenz curve numerically yields</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="ch3.html#cb176-1" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">integral</span>(lorenz_fun, <span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb176-2"><a href="ch3.html#cb176-2" tabindex="-1"></a>gini <span class="ot">=</span> <span class="dv">1-2</span><span class="sc">*</span>B</span>
<span id="cb176-3"><a href="ch3.html#cb176-3" tabindex="-1"></a>gini</span></code></pre></div>
<pre><code>## [1] 0.4410313</code></pre>
<p>so the Gini coefficient in the FRS data is 0.44. This seems in line with estimates from administrative data for income from all sources before taxes. Unlike other numerical measures, the scale of the Gini coefficient is difficult to interpret in itself. However, as all numerical measures it is useful for comparing the inequality of different distributions, e.g., between countries, or within a country over time, as we see below.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="ch3.html#cb178-1" tabindex="-1"></a><span class="co"># Clear R environment</span></span>
<span id="cb178-2"><a href="ch3.html#cb178-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span></code></pre></div>
</div>
</div>
</div>
</div>
<div id="cross-country-differences-in-income-inequality" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Cross-country differences in income inequality<a href="ch3.html#cross-country-differences-in-income-inequality" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <a href="https://wid.world/">World Inequality Database</a> provides open access to the most extensive available database on the historical evolution of the world distribution of income and wealth, both within countries and between countries.</p>
<p>This section uses cross sectional data of countries on a set of measures of income inequality in 2017. The data comes from <span class="citation">Alvaredo and Saez (<a href="#ref-wid">2022</a>)</span>, and is available <a href="https://wid.world/data/">here</a>. For ease of replication, the data has been saved in the sheet <code>WID17</code> of the <code>data_ch3.xlsx</code> Excel file.</p>
<p>Load the data and print first few rows</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="ch3.html#cb179-1" tabindex="-1"></a>wid2017 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;data_ch3.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;WID2017&quot;</span>)</span>
<span id="cb179-2"><a href="ch3.html#cb179-2" tabindex="-1"></a>wid2017<span class="sc">$</span>Country <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wid2017<span class="sc">$</span>Country)</span>
<span id="cb179-3"><a href="ch3.html#cb179-3" tabindex="-1"></a><span class="fu">head</span>(wid2017)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Country"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Year"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["gini"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["s10"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["s1"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["s0.1"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["p90p50"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["p50p10"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"Argentina","2":"2017","3":"0.5813541","4":"46.41","5":"13.86","6":"2.980000","7":"3.437194","8":"NA"},{"1":"Australia","2":"2017","3":"0.4877812","4":"34.39","5":"10.04","6":"3.120000","7":"2.525910","8":"7.874346"},{"1":"Belarus","2":"2017","3":"0.4325843","4":"32.99","5":"10.13","6":"3.170000","7":"2.247648","8":"4.615687"},{"1":"Belgium","2":"2017","3":"0.4362829","4":"31.83","5":"8.50","6":"2.270000","7":"2.325703","8":"5.413072"},{"1":"Brazil","2":"2017","3":"0.6820930","4":"58.43","5":"20.92","6":"5.350000","7":"4.203892","8":"NA"},{"1":"Bulgaria","2":"2017","3":"0.5486084","4":"44.34","5":"19.64","6":"9.099999","7":"2.747617","8":"5.460958"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The dataset contains observations for 48 countries in 2017, on 6 aggregate measures of inequality in pre-tax income.
- <code>gini</code> is the Gini coefficient
- <code>s10</code>, <code>s1</code>, and <code>s0.1</code> are the income shares of the top 10%, 1%, and 0.1%
- <code>p90p50</code> and <code>p50p10</code> are the P90P50 and P50P10 percentile ratios.</p>
<p>To get a sense of the data, report a set of summary statistics</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="ch3.html#cb180-1" tabindex="-1"></a><span class="fu">summary</span>(wid2017)</span></code></pre></div>
<pre><code>##       Country        Year           gini             s10              s1       
##  Argentina: 1   Min.   :2017   Min.   :0.3779   Min.   :27.47   Min.   : 7.05  
##  Australia: 1   1st Qu.:2017   1st Qu.:0.4394   1st Qu.:33.18   1st Qu.:10.50  
##  Belarus  : 1   Median :2017   Median :0.5072   Median :37.73   Median :12.86  
##  Belgium  : 1   Mean   :2017   Mean   :0.5192   Mean   :40.84   Mean   :14.35  
##  Brazil   : 1   3rd Qu.:2017   3rd Qu.:0.5809   3rd Qu.:46.89   3rd Qu.:17.65  
##  Bulgaria : 1   Max.   :2017   Max.   :0.7442   Max.   :64.19   Max.   :27.06  
##  (Other)  :42                                                                  
##       s0.1            p90p50          p50p10     
##  Min.   : 1.640   Min.   :1.676   Min.   :4.578  
##  1st Qu.: 3.397   1st Qu.:2.237   1st Qu.:5.080  
##  Median : 4.660   Median :2.656   Median :5.403  
##  Mean   : 4.915   Mean   :2.926   Mean   :5.589  
##  3rd Qu.: 5.575   3rd Qu.:3.452   3rd Qu.:5.903  
##  Max.   :12.670   Max.   :6.179   Max.   :8.298  
##                                   NA&#39;s   :8</code></pre>
<p>It is immediately observed, that there are large differences in the values of all income-inequality metrics across countries. For example, the income share of the top 0.1 % of individuals varies from 1.6% to 12.67% across countries.</p>
<p>Given the relatively small number of observations, a convenient way to represent cross country differences is through ordered bar charts. Arranging countries in increasing order of Gini coefficients, and representing the value of each country’s Gini coefficient by the height of the corresponding bar yields</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="ch3.html#cb182-1" tabindex="-1"></a><span class="fu">ggplot</span>(wid2017) <span class="sc">+</span> </span>
<span id="cb182-2"><a href="ch3.html#cb182-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_reorder</span>(Country, gini), <span class="at">y=</span>gini), <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb182-3"><a href="ch3.html#cb182-3" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>)) <span class="sc">+</span> </span>
<span id="cb182-4"><a href="ch3.html#cb182-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Gini coefficient&quot;</span>) <span class="sc">+</span></span>
<span id="cb182-5"><a href="ch3.html#cb182-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gini coefficients across countries&quot;</span>, </span>
<span id="cb182-6"><a href="ch3.html#cb182-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Pre-tax income from all sources&quot;</span>) <span class="sc">+</span></span>
<span id="cb182-7"><a href="ch3.html#cb182-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>We observe large cross-country differences in terms of Gini coefficients. Within the sample, in terms of Gini coefficients, Slovakia has the most equal income distribution (0.378) and Mexico has the most unequal income distribution (0.744).</p>
<p>Producing similar graphs for the other metrics</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="ch3.html#cb183-1" tabindex="-1"></a><span class="fu">ggplot</span>(wid2017) <span class="sc">+</span> </span>
<span id="cb183-2"><a href="ch3.html#cb183-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_reorder</span>(Country, s10), <span class="at">y=</span>s10), <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb183-3"><a href="ch3.html#cb183-3" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>)) <span class="sc">+</span> </span>
<span id="cb183-4"><a href="ch3.html#cb183-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Top 10 % income share&quot;</span>) <span class="sc">+</span></span>
<span id="cb183-5"><a href="ch3.html#cb183-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Top 10% income shares across countries&quot;</span>, </span>
<span id="cb183-6"><a href="ch3.html#cb183-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Pre-tax income from all sources&quot;</span>) <span class="sc">+</span></span>
<span id="cb183-7"><a href="ch3.html#cb183-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="ch3.html#cb184-1" tabindex="-1"></a><span class="fu">ggplot</span>(wid2017) <span class="sc">+</span> </span>
<span id="cb184-2"><a href="ch3.html#cb184-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_reorder</span>(Country, s1), <span class="at">y=</span>s1), <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb184-3"><a href="ch3.html#cb184-3" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>)) <span class="sc">+</span> </span>
<span id="cb184-4"><a href="ch3.html#cb184-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Top 1% income share&quot;</span>) <span class="sc">+</span></span>
<span id="cb184-5"><a href="ch3.html#cb184-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Top 1% income shares across countries&quot;</span>, </span>
<span id="cb184-6"><a href="ch3.html#cb184-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Pre-tax income from all sources&quot;</span>) <span class="sc">+</span></span>
<span id="cb184-7"><a href="ch3.html#cb184-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="ch3.html#cb185-1" tabindex="-1"></a><span class="fu">ggplot</span>(wid2017) <span class="sc">+</span> </span>
<span id="cb185-2"><a href="ch3.html#cb185-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_reorder</span>(Country, p90p50), <span class="at">y=</span>p90p50), <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb185-3"><a href="ch3.html#cb185-3" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>)) <span class="sc">+</span> </span>
<span id="cb185-4"><a href="ch3.html#cb185-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;P90P50 ratio&quot;</span>) <span class="sc">+</span></span>
<span id="cb185-5"><a href="ch3.html#cb185-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;P90P50 ratio across countries&quot;</span>, </span>
<span id="cb185-6"><a href="ch3.html#cb185-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Pre-tax income from all sources&quot;</span>) <span class="sc">+</span></span>
<span id="cb185-7"><a href="ch3.html#cb185-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="ch3.html#cb186-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(wid2017, <span class="sc">!</span><span class="fu">is.na</span>(p50p10))) <span class="sc">+</span> </span>
<span id="cb186-2"><a href="ch3.html#cb186-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_reorder</span>(Country, p50p10), <span class="at">y=</span>p50p10), <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;red&quot;</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb186-3"><a href="ch3.html#cb186-3" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>)) <span class="sc">+</span> </span>
<span id="cb186-4"><a href="ch3.html#cb186-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;P50P10 ratio&quot;</span>) <span class="sc">+</span></span>
<span id="cb186-5"><a href="ch3.html#cb186-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;P50P10 ratio across countries&quot;</span>, </span>
<span id="cb186-6"><a href="ch3.html#cb186-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Pre-tax income from all sources&quot;</span>) <span class="sc">+</span></span>
<span id="cb186-7"><a href="ch3.html#cb186-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>we observe that there are significant differences in terms of all different measures. Of course, different measures capture different aspects of inequality (e.g., Gini coefficients and top income shares in particular are measures of concentration, while the percentile ratios measure specific aspects of dispersion).</p>
<p>Nonetheless, inspecting the graphs, it seems countries with high inequality in one measure, tend to also exhibit high inequality in terms of the other measures. To inspect this relationship more clearly we next present scatterplots showing the association netween Gini coefficients and other metrics.</p>
<p>In terms of Gini coefficient and top income shares</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="ch3.html#cb187-1" tabindex="-1"></a><span class="fu">ggplot</span>(wid2017, <span class="fu">aes</span>(<span class="at">x=</span>gini)) <span class="sc">+</span> </span>
<span id="cb187-2"><a href="ch3.html#cb187-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>s10, <span class="at">col=</span><span class="st">&quot;Top 10%&quot;</span>)) <span class="sc">+</span></span>
<span id="cb187-3"><a href="ch3.html#cb187-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>s1, <span class="at">col=</span><span class="st">&quot;Top 1%&quot;</span>)) <span class="sc">+</span></span>
<span id="cb187-4"><a href="ch3.html#cb187-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>s0<span class="fl">.1</span>, <span class="at">col=</span><span class="st">&quot;Top 0.1%&quot;</span>)) <span class="sc">+</span></span>
<span id="cb187-5"><a href="ch3.html#cb187-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Gini coefficient&quot;</span>) <span class="sc">+</span></span>
<span id="cb187-6"><a href="ch3.html#cb187-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Measure&quot;</span>) <span class="sc">+</span></span>
<span id="cb187-7"><a href="ch3.html#cb187-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatterplot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Association between Gini coefficient and top income shares,  countries&quot;</span>, <span class="at">col =</span> <span class="st">&quot;Income share&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>unsurprisingly, we observe very strong positive association - countries with high Gini coefficients tend to also have high top income shares. Of course, this is not surprising as both Gini coefficients and top income shares are fundamentally measures of concentration, capturing similar aspects of income distributions within countries.</p>
<p>Perhaps more surprisingly, we observe also very strong association between Gini coefficients and percentile ratios:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="ch3.html#cb188-1" tabindex="-1"></a><span class="fu">ggplot</span>(wid2017, <span class="fu">aes</span>(<span class="at">x=</span>gini)) <span class="sc">+</span></span>
<span id="cb188-2"><a href="ch3.html#cb188-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>p50p10, <span class="at">col=</span><span class="st">&quot;P50P10&quot;</span>)) <span class="sc">+</span></span>
<span id="cb188-3"><a href="ch3.html#cb188-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>p90p50, <span class="at">col=</span><span class="st">&quot;P90P50&quot;</span>)) <span class="sc">+</span></span>
<span id="cb188-4"><a href="ch3.html#cb188-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Gini coefficient&quot;</span>) <span class="sc">+</span></span>
<span id="cb188-5"><a href="ch3.html#cb188-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Measure&quot;</span>) <span class="sc">+</span></span>
<span id="cb188-6"><a href="ch3.html#cb188-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatterplot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Association between Gini coefficient and percentile ratios, countries&quot;</span>, <span class="at">col =</span> <span class="st">&quot;Measure&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>In general, the data shows that there are large and systematic differences in income inequality across countries.</p>
</div>
<div id="income-inequality-over-time" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Income inequality over time<a href="ch3.html#income-inequality-over-time" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section uses a panel dataset for several large developped economies, tracking measures of income inequality from the begining of the 20th century, until 2022. As in the previous section, the data comes from <span class="citation">Alvaredo and Saez (<a href="#ref-wid">2022</a>)</span> and is available <a href="https://wid.world/data/">here</a> The . For ease of replication, the data has been saved in the sheet <code>WIDpanel</code> of the <code>data_ch3.xlsx</code> Excel file.</p>
<p>Load the data and print first few rows</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="ch3.html#cb189-1" tabindex="-1"></a>panel <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;data_ch3.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;WIDpanel&quot;</span>)</span>
<span id="cb189-2"><a href="ch3.html#cb189-2" tabindex="-1"></a>panel<span class="sc">$</span>Country <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(panel<span class="sc">$</span>Country)</span>
<span id="cb189-3"><a href="ch3.html#cb189-3" tabindex="-1"></a><span class="fu">head</span>(panel)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Country"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Year"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["gini"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["s10"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["s1"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["s0.1"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"Australia","2":"1912","3":"0.5565278","4":"42.44","5":"15.86","6":"6.97"},{"1":"Australia","2":"1913","3":"0.5316099","4":"39.00","5":"14.56","6":"6.34"},{"1":"Australia","2":"1914","3":"0.5146982","4":"36.68","5":"13.69","6":"6.00"},{"1":"Australia","2":"1915","3":"0.4988307","4":"34.51","5":"12.97","6":"5.78"},{"1":"Australia","2":"1916","3":"0.4648253","4":"29.95","5":"11.15","6":"5.05"},{"1":"Australia","2":"1917","3":"0.4699681","4":"30.61","5":"11.48","6":"5.19"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>We have a panel data in long form, with records of the Gini coefficient and Top 10%, Top 1% and Top 0.1 % income shares, for each country in each year, from 1912 until 2021.</p>
<p>The set of countries included</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="ch3.html#cb190-1" tabindex="-1"></a><span class="fu">levels</span>(panel<span class="sc">$</span>Country)</span></code></pre></div>
<pre><code>## [1] &quot;Australia&quot;      &quot;Canada&quot;         &quot;France&quot;         &quot;Germany&quot;       
## [5] &quot;Japan&quot;          &quot;United Kingdom&quot; &quot;United States&quot;</code></pre>
<p>are large developed economies.</p>
<p>Plotting time series plots of Gini coefficient across time, for each country yields</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="ch3.html#cb192-1" tabindex="-1"></a><span class="fu">ggplot</span>(panel, <span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>gini, <span class="at">col=</span>Country)) <span class="sc">+</span> </span>
<span id="cb192-2"><a href="ch3.html#cb192-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb192-3"><a href="ch3.html#cb192-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb192-4"><a href="ch3.html#cb192-4" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Dark2&quot;</span>) <span class="sc">+</span></span>
<span id="cb192-5"><a href="ch3.html#cb192-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Gini coefficient&quot;</span>) <span class="sc">+</span></span>
<span id="cb192-6"><a href="ch3.html#cb192-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Time series line plot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Gini coefficient over time&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>We can see that data on Gini coefficient for Australia, Canada, France and US are available since 1912, but for the rest data only becomes available late in the second half of the 20th century.</p>
<p>While there are some differences across countries, the overall pattern can be summarized as follows:
- income inequality (measured by Gini coefficient) was relatively high in the beginning of the 20th century and remained elevated until the 1930s-1940s, when it decreased substantially.
- inequality remained relatively low for the next several decades, starting to pick up again at various points in the 1970s.
- since then inequality has been overall increasing.</p>
<p>This pattern is well known and documented. While various explanations for it have been proposed, a discussion is beyond the scope of this document.</p>
<p>However, something that we can check in our data is whether the evolution of inequality in terms of Gini coefficients is similar to the evolution in terms of other measures. Unsurprisingly, it turns out that top income shares have followed a similar pattern:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="ch3.html#cb193-1" tabindex="-1"></a><span class="fu">ggplot</span>(panel, <span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>s10, <span class="at">col=</span>Country)) <span class="sc">+</span> </span>
<span id="cb193-2"><a href="ch3.html#cb193-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb193-3"><a href="ch3.html#cb193-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb193-4"><a href="ch3.html#cb193-4" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Dark2&quot;</span>) <span class="sc">+</span></span>
<span id="cb193-5"><a href="ch3.html#cb193-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Top 10% income share&quot;</span>) <span class="sc">+</span></span>
<span id="cb193-6"><a href="ch3.html#cb193-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Time series line plot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Top 10% income share over time&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="ch3.html#cb194-1" tabindex="-1"></a><span class="fu">ggplot</span>(panel, <span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>s1, <span class="at">col=</span>Country)) <span class="sc">+</span> </span>
<span id="cb194-2"><a href="ch3.html#cb194-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb194-3"><a href="ch3.html#cb194-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb194-4"><a href="ch3.html#cb194-4" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Dark2&quot;</span>) <span class="sc">+</span></span>
<span id="cb194-5"><a href="ch3.html#cb194-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Top 1% income share&quot;</span>) <span class="sc">+</span></span>
<span id="cb194-6"><a href="ch3.html#cb194-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Time series line plot&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Top 1% income share over time&quot;</span>)</span></code></pre></div>
<p><img src="04-Ch3_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>In summary, we observe a common pattern across a set of large developped economies, where income inequality has followed a U-shaped pattern over time for the last 100 years or so. At present, measures of inequality are elevated relative to the norm of the middle of the 20th century.</p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Alvaredo, P., Atkinson, Saez, 2022. <a href="https://wid.world/">World inequality database</a>.
</div>
<div class="csl-entry">
Global Carbon Budget, 2022a. <a href="https://globalcarbonbudget.org/">Annual CO2 emissions</a>.
</div>
<div class="csl-entry">
Global Carbon Budget, 2022b. <a href="https://globalcarbonbudget.org/">Annual CO2 emissions</a>.
</div>
<div class="csl-entry">
MEaSUREs, 2023. Global mean sea level trend from integrated multi-mission ocean altimeters TOPEX/poseidon, jason-1, OSTM/jason-2, and jason-3 version 5.1. <a href="https://doi.org/10.5067/GMSLM-TJ151">https://doi.org/10.5067/GMSLM-TJ151</a>
</div>
<div class="csl-entry">
Met Office, 2023a. <a href="https://beta.gss-data.org.uk/cube/explore?uri=https%3A%2F%2Fraw.githubusercontent.com%2FGSS-Cogs%2Fprovider-met-office%2Fmain%2Fout%2Fregional-average-climate-observations-uk-annual-mean-temperature-2022%2Fregional-average-climate-observations-uk-annual-mean-temperature-2022%2Fregional-average-climate-observations-uk-annual-mean-temperature-2022.csv%23dataset-catalog-entry">Data for the regional average mean temperature with trends 1884 - 2022</a>.
</div>
<div class="csl-entry">
Met Office, 2023b. <a href="https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fmet-office-regional-average-climate-observations-uk-annual-rainfall-2021%2Fregional-average-climate-observations-uk-annual-rainfall%23dataset-catalog-entry&amp;show-uris=false">Regional average climate observations, UK annual rainfall</a>.
</div>
<div class="csl-entry">
NASA/JPL, 2019. JPL GRACE and GRACE-FO mascon ocean, ice, and hydrology equivalent water height release 06 version 02. <a href="https://doi.org/10.5067/TEMSC-3MJ62">https://doi.org/10.5067/TEMSC-3MJ62</a>
</div>
<div class="csl-entry">
Office for National Statistics, Social and Vital Statistics Division, Department for Work and Pensions, National Centre for Social Research, 2023. Family resources survey, 2016-2017. https://doi.org/<a href="http://doi.org/10.5255/UKDA-SN-8336-1">http://doi.org/10.5255/UKDA-SN-8336-1</a>
</div>
<div class="csl-entry">
R Core Team, 2023. <a href="https://www.R-project.org/">R: A language and environment for statistical computing</a>. R Foundation for Statistical Computing, Vienna, Austria.
</div>
<div class="csl-entry">
Rohde, R.A., Hausfather, Z., 2020. The berkeley earth land/ocean temperature record. Earth System Science Data 12, 3469–3479. <a href="https://doi.org/10.5194/essd-12-3469-2020">https://doi.org/10.5194/essd-12-3469-2020</a>
</div>
<div class="csl-entry">
Tans and Keeling, 2023. <a href="https://gml.noaa.gov/ccgg/trends/data.html">Trends in atmospheric carbon dioxide</a>.
</div>
<div class="csl-entry">
Wickham, H., 2016. <a href="https://ggplot2.tidyverse.org">ggplot2: Elegant graphics for data analysis</a>. Springer-Verlag New York.
</div>
<div class="csl-entry">
World Bank, 2023. World development indicators. https://doi.org/<a href="https://doi.org/10.57966/6rwy-0b07">https://doi.org/10.57966/6rwy-0b07</a>
</div>
</div>
</div>
</div>















<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-wid" class="csl-entry">
Alvaredo, P., Atkinson, Saez, 2022. <a href="https://wid.world/">World inequality database</a>.
</div>
<div id="ref-frs17" class="csl-entry">
Office for National Statistics, Social and Vital Statistics Division, Department for Work and Pensions, National Centre for Social Research, 2023. Family resources survey, 2016-2017. https://doi.org/<a href="http://doi.org/10.5255/UKDA-SN-8336-1">http://doi.org/10.5255/UKDA-SN-8336-1</a>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch2.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
